# Exercise: Mutli-variable Regression

Your task is to do the following:

1. Load the data
2. Explore the data
3. Identify the features and their types
4. Identify the target and its type
5. Initialize a regression model
6. Train the model
7. Evaluate the model
8. Make predictions on new cases of your choice

The dataset progressively gets more complex.

1. The Advertising Dataset has only `3` numerical features, with `200` samples
2. The Auto MPG Dataset has `5` numerical features and `3` categorical features, with `398` samples
3. The California Housing Prices Dataset has `8` numerical features and `1` categorical, with `20,640` samples
4. Finally, the Abalone Dataset will require you to do more reading and understanding of the dataset, before you can use it.

In [ ]:
import pandas as pd

## 1. Advertising Dataset

The Advertising Dataset is a fundamental resource in statistical learning and regression analysis. It is primarily known for its use in the first chapter of the seminal textbook "An Introduction to Statistical Learning" (ISLR) by Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani.

The dataset is used to illustrate the relationship between advertising budgets across different media and the resulting product sales.

- Features: `3` numerical
- Target: `sales` of the product (in thousands of units).
- Size: `200` samples.
- Source: [Advertising Dataset](https://www.statlearning.com/s/Advertising.csv)

In [ ]:
pd.read_csv("../datasets/advertising.csv").head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [ ]:
# INSERT YOUR CODE

## 2. Auto MPG Dataset

The Auto MPG Dataset is a classic benchmark for regression analysis in machine learning. It originally appeared in the 1983 American Statistical Association (ASA) Exposition and was later donated to the UCI Machine Learning Repository by Ross Quinlan in 1993.

The data consists of technical specifications for various car models from the late 1970s and early 1980s, primarily used to predict fuel efficiency (MPG).

- Features: `5` numerical, `3` categorical
- Target: `mpg` (miles per gallon)
- Size: `398` samples
- Source: [Auto MPG Dataset](https://archive.ics.uci.edu/dataset/9/auto+mpg)

In [10]:
pd.read_csv("../datasets/auto-mpg.csv").head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [ ]:
# INSERT YOUR CODE

## 3. California Housing Prices Dataset

Find and download the dataset from Kaggle at [California Housing Dataset](https://www.kaggle.com/datasets/dhirajnirne/california-housing-data).

According to [keras.io](https://keras.io/api/datasets/california_housing/):
 
> This dataset was obtained from the StatLib repository.
> 
> It's a continuous regression dataset with 20,640 samples with 8 features each.
> 
> The target variable is a scalar: the median house value for California districts, in dollars.
> 
> The 8 input features are the following:
> 
> - MedInc: median income in block group
> - HouseAge: median house age in block group
> - AveRooms: average number of rooms per household
> - AveBedrms: average number of bedrooms per household
> - Population: block group population
> - AveOccup: average number of household members
> - Latitude: block group latitude
> - Longitude: block group longitude
> 
> This dataset was derived from the 1990 U.S. census, using one row per census block group. A block group is the smallest geographical unit for which the U.S. Census Bureau publishes sample data (a block group typically has a population of 600 to 3,000 people).
> 
> A household is a group of people residing within a home. Since the average number of rooms and bedrooms in this dataset are provided per household, these columns may take surprisingly large values for block groups with few households and many empty houses, such as vacation resorts.

In [ ]:
pd.read_csv("../datasets/california_housing.csv").head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [ ]:
# INSERT YOUR CODE

## 4. Abalone Dataset

Predicting the age of abalone from physical measurements.

A real challenge is different formats, hence we present this to you as an opportunity to practice dealling with this problem:

1. Visit the [dataset page](https://archive.ics.uci.edu/dataset/1/abalone) and click the **"Download"** button.
    - You will read the page yourself to understand the purpose of this data, and what you are supposed to do.
    - You will notice that it is not simply a `.csv` file. Rather, `3` different files, compressed.
2. Find out how to read it correctly as a DataFrame for exploratory data analysis
3. Finally, train a regression model on the features and the target

In [ ]:
# INSERT YOUR CODE

Find more datasets on [UCI Machine Learning Repository](https://archive.ics.uci.edu/datasets).